# Generated by Django 5.2.17 on 2026-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['empresa', 'nome'], name='idx_cliente_empresa_nome')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_cliente_empresa_codigo')],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produtos',
                'indexes': [models.Index(fields=['empresa', 'nome'], name='idx_produto_empresa_nome')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_produto_empresa_codigo')],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicos',
                'indexes': [models.Index(fields=['empresa', 'descricao'], name='idx_servico_empresa_descricao')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_servico_empresa_codigo')],
            },
        ),
    ]
