services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ordem_servico_web
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: ordem_servico_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
